// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoyzgeviphxswhdvaawf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlveXpnZXZpcGh4c3doZHZhYXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MjkwNzEsImV4cCI6MjA2ODMwNTA3MX0.e3xUGr_ZjIBNLTNq1ecp3HK3EficALtxXRgFZZgpPos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);